### ISSUE TITLE
version 0.4 broken when using venv with Python 3.x

### ISSUE THREAD

**Issue by glasswalk3r** [candlepin/python-iniparse#3]
I just tested this, both on Ubuntu 18.04 and CentOS 7.6.1810, with the same results:

```
(venv) [vagrant@localhost siebel-crash-report]$ pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.3, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/vagrant/siebel-crash-report, inifile:
collected 0 items / 1 errors                                                                                                                                                                 

=========================================================================================== ERRORS ===========================================================================================
__________________________________________________________________ ERROR collecting tests/siebel/maintenance/test_thread.py __________________________________________________________________
ImportError while importing test module '/home/vagrant/siebel-crash-report/tests/siebel/maintenance/test_thread.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/siebel/maintenance/test_thread.py:1: in <module>
    from siebel.maintenance.crash import fix_thread_id
src/siebel/maintenance/crash.py:6: in <module>
    from iniparse import INIConfig
venv/lib64/python3.6/site-packages/iniparse/__init__.py:6: in <module>
    from ini import INIConfig, change_comment_syntax
E   ModuleNotFoundError: No module named 'ini'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================== 1 error in 0.12 seconds ===================================================================================
(venv) [vagrant@localhost siebel-crash-report]$ pip show iniparse
Name: iniparse
Version: 0.4
Summary: Accessing and Modifying INI files
Home-page: http://code.google.com/p/iniparse/
Author: Paramjit Oberoi
Author-email: param@cs.wisc.edu
License: MIT
Location: /home/vagrant/siebel-crash-report/venv/lib/python3.6/site-packages
Requires: 
Required-by: 
(venv) [vagrant@localhost siebel-crash-report]$
```

Now, if I go out the venv and install `iniparse` globally (at least for Ubuntu there is a DEB package for that, couldn't find for CentOS though), I can start a interactive session and import the module without the same exception:

```
$ python3.6 -V
Python 3.6.7
alceu@yggdrasil:~/Projetos/siebel-crash-report$ python3.6
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from iniparse import INIConfig
>>> 
```

As soon as I create a new venv and try to repeat those steps, same errors occur. I can't install `ini` either:

```
$ python3.6 -m venv venv
$ source venv/bin/activate
(venv) $ pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d7/41/34dd96bd33958e52cb4da2f1bf0818e396514fd4f4725a79199564cd0c20/pip-19.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.2
(venv) $ pip install -r requirements-3x.txt 
Collecting atomicwrites==1.3.0 (from -r requirements-3x.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs==18.2.0 (from -r requirements-3x.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting configparser==3.7.1 (from -r requirements-3x.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/43/63/220afe02a0d302c2244309b1dce3d884a865be65c7d8148ededfc0c29c31/configparser-3.7.1-py3-none-any.whl
Collecting entrypoints==0.3 (from -r requirements-3x.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements-3x.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting flake8==3.7.5 (from -r requirements-3x.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/5a/d8/1377549a9b77ad6d3c8161c741e2186bc698150f639fe08123bfe53e7a27/flake8-3.7.5-py2.py3-none-any.whl
Collecting funcsigs==1.0.2 (from -r requirements-3x.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting iniparse==0.4 (from -r requirements-3x.txt (line 8))
Collecting mccabe==0.6.1 (from -r requirements-3x.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting more-itertools==5.0.0 (from -r requirements-3x.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/a4/a6/42f17d065bda1fac255db13afc94c93dbfb64393eae37c749b4cb0752fc7/more_itertools-5.0.0-py3-none-any.whl
Collecting pathlib2==2.3.3 (from -r requirements-3x.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting pluggy==0.8.1 (from -r requirements-3x.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/2d/60/f58d9e8197f911f9405bf7e02227b43a2acc2c2f1a8cbb1be5ecf6bfd0b8/pluggy-0.8.1-py2.py3-none-any.whl
Collecting py==1.7.0 (from -r requirements-3x.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
Collecting pycodestyle==2.5.0 (from -r requirements-3x.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting pyflakes==2.1.0 (from -r requirements-3x.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/16/3b/b6a508ad148ce1ef50bd7a9a783afbb8d775616fc4ae5e3007c8815a3c85/pyflakes-2.1.0-py2.py3-none-any.whl
Collecting pytest==4.2.0 (from -r requirements-3x.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/0d/c4/8093b4ffdde66628d4cb138d1d53726e2c21c23ac397cb75494e3f4310c9/pytest-4.2.0-py2.py3-none-any.whl
Collecting scandir==1.9.0 (from -r requirements-3x.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz
Collecting simplejson==3.16.0 (from -r requirements-3x.txt (line 18))
Collecting six==1.12.0 (from -r requirements-3x.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting typing==3.6.6 (from -r requirements-3x.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from pytest==4.2.0->-r requirements-3x.txt (line 16)) (39.0.1)
Installing collected packages: atomicwrites, attrs, configparser, entrypoints, enum34, pyflakes, mccabe, pycodestyle, flake8, funcsigs, iniparse, six, more-itertools, pathlib2, pluggy, py, pytest, scandir, simplejson, typing
  Running setup.py install for scandir ... done
Successfully installed atomicwrites-1.3.0 attrs-18.2.0 configparser-3.7.1 entrypoints-0.3 enum34-1.1.6 flake8-3.7.5 funcsigs-1.0.2 iniparse-0.4 mccabe-0.6.1 more-itertools-5.0.0 pathlib2-2.3.3 pluggy-0.8.1 py-1.7.0 pycodestyle-2.5.0 pyflakes-2.1.0 pytest-4.2.0 scandir-1.9.0 simplejson-3.16.0 six-1.12.0 typing-3.6.6
$ export PYTHONPATH=$PWD/src
(venv) $ pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.7, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/alceu/Projetos/siebel-crash-report, inifile:
collected 0 items / 1 errors                                                                                                                                                                 

=========================================================================================== ERRORS ===========================================================================================
__________________________________________________________________ ERROR collecting tests/siebel/maintenance/test_thread.py __________________________________________________________________
ImportError while importing test module '/home/alceu/Projetos/siebel-crash-report/tests/siebel/maintenance/test_thread.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/siebel/maintenance/test_thread.py:1: in <module>
    from siebel.maintenance.crash import fix_thread_id
src/siebel/maintenance/crash.py:6: in <module>
    from iniparse import INIConfig
venv/lib/python3.6/site-packages/iniparse/__init__.py:6: in <module>
    from ini import INIConfig, change_comment_syntax
E   ModuleNotFoundError: No module named 'ini'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================== 1 error in 0.22 seconds ===================================================================================
(venv) $ pip install ini
Collecting ini
  Using cached https://files.pythonhosted.org/packages/92/1f/d517f2ceedbe608efd077f431fee77f2344f98aa3f5432f27c11c155d8b3/INI-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_0441lo5/ini/setup.py", line 12, in <module>
        import ini
      File "/tmp/pip-install-_0441lo5/ini/ini.py", line 13, in <module>
        from itertools import imap
    ImportError: cannot import name 'imap'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_0441lo5/ini/
(venv) $
```

**Comment by glasswalk3r** [comment]
Gave another shot with Ubuntu 18.04, by not creating a venv and installing the module globally as a DEB package:

```
$ sudo apt-get install -y python3-pytest
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
The following additional packages will be installed:
  python3-attr python3-pluggy python3-py
Pacotes sugeridos:
  python-attr-doc
Os NOVOS pacotes a seguir serão instalados:
  python3-attr python3-pluggy python3-py python3-pytest
É preciso baixar 244 kB de arquivos.
Depois desta operação, 1.177 kB adicionais de espaço em disco serão usados.
Obter:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-attr all 17.4.0-2 [23,8 kB]
Obter:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-pluggy all 0.6.0-1 [12,3 kB]
Obter:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-py all 1.5.2-1 [65,2 kB]
Obter:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-pytest all 3.3.2-2 [142 kB]
Baixados 244 kB em 2s (146 kB/s)      
A seleccionar pacote anteriormente não seleccionado python3-attr.
(Lendo banco de dados ... 418339 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../python3-attr_17.4.0-2_all.deb ...
A descompactar python3-attr (17.4.0-2) ...
A seleccionar pacote anteriormente não seleccionado python3-pluggy.
A preparar para desempacotar .../python3-pluggy_0.6.0-1_all.deb ...
A descompactar python3-pluggy (0.6.0-1) ...
A seleccionar pacote anteriormente não seleccionado python3-py.
A preparar para desempacotar .../python3-py_1.5.2-1_all.deb ...
A descompactar python3-py (1.5.2-1) ...
A seleccionar pacote anteriormente não seleccionado python3-pytest.
A preparar para desempacotar .../python3-pytest_3.3.2-2_all.deb ...
A descompactar python3-pytest (3.3.2-2) ...
Configurando python3-py (1.5.2-1) ...
Configurando python3-pluggy (0.6.0-1) ...
Configurando python3-attr (17.4.0-2) ...
A processar 'triggers' para man-db (2.8.3-2) ...
Configurando python3-pytest (3.3.2-2) ...
$ 
$ python3.6 -m pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.7, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/alceu/Projetos/siebel-crash-report, inifile:
collected 3 items                                                                                                                                                                            

tests/siebel/maintenance/test_thread.py ...                                                                                                                                            [100%]

================================================================================== 3 passed in 0.03 seconds ==================================================================================

```

**Comment by KyleKing** [comment]
I also ran into the `ModuleNotFoundError: No module named 'ini'` error when I accidentally installed the Python 2 `iniparse` version from pypi. The package fails to import the relative file `ini.py` because that file imports `ConfigParser`, which isn't available in Python 3 (all lowercase `configparser` in Python 3)

**Comment by jirihnidek** [comment]
@glasswalk3r Hi, I just published new release of iniparse on pypi.org. It should work with Python 3.x. Please can you test it?

**Comment by jhasse** [comment]
Works for me! Thanks :)

**Comment by jirihnidek** [comment]
@glasswalk3r I'm closing this bug, because it seems that this issues is fixed now. In case you will have any trouble feel free to reopen this issue or create new one.

**Comment by glasswalk3r** [comment]
Hi, sorry for being late!

Here is what I got:

```
alceu@yggdrasil:~$ pip install iniparse
Collecting iniparse
  Using cached iniparse-0.5-py3-none-any.whl (24 kB)
Requirement already satisfied: six in ./.pyenv/versions/3.6.8/lib/python3.6/site-packages (from iniparse) (1.14.0)
Installing collected packages: iniparse
Successfully installed iniparse-0.5
alceu@yggdrasil:~$ python
Python 3.6.8 (default, Sep 29 2019, 21:28:42) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from iniparse import INIConfig
>>> 
```

Now from a more recent Cpython:

```
alceu@yggdrasil:~$ pip install iniparse
Collecting iniparse
  Using cached iniparse-0.5-py3-none-any.whl (24 kB)
Requirement already satisfied: six in ./.pyenv/versions/3.8.0b4/lib/python3.8/site-packages (from iniparse) (1.13.0)
Installing collected packages: iniparse
Successfully installed iniparse-0.5
alceu@yggdrasil:~$ python
Python 3.8.0b4 (default, Nov  9 2019, 17:47:40) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from iniparse import INIConfig
>>> 
```

Looking good! Thank you!
