### ISSUE TITLE
cfgparser.1 missing when running tests 

### ISSUE THREAD

**Issue by litios** [candlepin/python-iniparse#30]
## Issue

When running the tests either from tox or runtests.py I get several failed tests:

```
======================================================================
FAIL: test_read_returns_file_list (tests.test_compat.RawConfigParserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python-iniparse/tests/test_compat.py", line 280, in test_read_returns_file_list
    self.assertEqual(parsed_files, [file1])
AssertionError: Lists differ: [] != ['cfgparser.1']

Second list contains 1 additional elements.
First extra element 0:
'cfgparser.1'

- []
+ ['cfgparser.1']

======================================================================
FAIL: test_read_returns_file_list (tests.test_compat.ConfigParserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python-iniparse/tests/test_compat.py", line 280, in test_read_returns_file_list
    self.assertEqual(parsed_files, [file1])
AssertionError: Lists differ: [] != ['cfgparser.1']

Second list contains 1 additional elements.
First extra element 0:
'cfgparser.1'

- []
+ ['cfgparser.1']

======================================================================
FAIL: test_read_returns_file_list (tests.test_compat.SafeConfigParserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python-iniparse/tests/test_compat.py", line 280, in test_read_returns_file_list
    self.assertEqual(parsed_files, [file1])
AssertionError: Lists differ: [] != ['cfgparser.1']

Second list contains 1 additional elements.
First extra element 0:
'cfgparser.1'

- []
+ ['cfgparser.1']

----------------------------------------------------------------------
Ran 96 tests in 0.039s

FAILED (failures=3, skipped=1
```

After inspecting the distro packages I noticed `cfgparser.1` is being created during the testing phase but there is no reference to this file anywhere else on this repository.

## Suggested fix

To prevent changing the workflow in the current distro packages, it would be desired to either:
* Update the tox script to create this file with the right contents before running the tests.
* Add information about this file and its contents (and how to test the package) in the README file.

**Comment by jirihnidek** [comment]
This issue was fixed in #29
