### ISSUE TITLE
Python 3.13.0b1: `AttributeError: module 'unittest' has no attribute 'makeSuite'`

### ISSUE THREAD

**Issue by mgorny** [candlepin/python-iniparse#31]
```pytb
$ python3.13 runtests.py 
/tmp/python-iniparse/tests/test_ini.py:29: SyntaxWarning: invalid escape sequence '\c'
  ('[se\ct%[ion\t]',     ('se\ct%[ion\t', None, None, -1)),
/tmp/python-iniparse/tests/test_ini.py:29: SyntaxWarning: invalid escape sequence '\c'
  ('[se\ct%[ion\t]',     ('se\ct%[ion\t', None, None, -1)),
/tmp/python-iniparse/tests/test_fuzz.py:58: SyntaxWarning: invalid escape sequence '\['
  name = re.sub(':|=| |\[', '', name)
Traceback (most recent call last):
  File "/tmp/python-iniparse/runtests.py", line 8, in <module>
    unittest.main(defaultTest='tests.Suite')
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/main.py", line 103, in __init__
    self.parseArgs(argv)
    ~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/unittest/main.py", line 142, in parseArgs
    self.createTests()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/unittest/main.py", line 153, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
                                                   self.module)
                                                   ^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/loader.py", line 207, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/loader.py", line 192, in loadTestsFromName
    test = obj()
  File "/tmp/python-iniparse/tests/__init__.py", line 19, in __init__
    test_ini.Suite(),
    ~~~~~~~~~~~~~~^^
  File "/tmp/python-iniparse/tests/test_ini.py", line 416, in __init__
    unittest.makeSuite(TestSectionLine, 'test'),
    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/__init__.py", line 80, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'unittest' has no attribute 'makeSuite'
```

**Comment by jirihnidek** [comment]
I believe that this issue was fixed in #32. If this issue persist, then please reopen this issue.
